spring:
  application:
    name: ticket.management.system

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: pass
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
app:
  token:
    secret-key: ${JWT_SECRET_KEY:Y29mcmUtZGUtc2VuaGFzLWFwaS1kZXBsb3k=}

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub