spring:
  application:
    name: ticket.management.system

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: America/Sao_Paulo
app:
  token:
    secret-key: ${JWT_SECRET_KEY}

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

notification:
  service:
    url: ${NOTIFICATION_URL}


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      orm:
        jdbc:
          bind: TRACE
