spring:
  application:
    name: ticket.management.system

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/ticket-management-db
    username:
    password:
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    time-zone: America/Sao_Paulo
app:
  token:
    secret-key: ${JWT_SECRET_KEY:Y29mcmUtZGUtc2VuaGFzLWFwaS1kZXBsb3k=}

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
