CREATE TABLE tb_ticket(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number INTEGER NOT NULL UNIQUE,
    title VARCHAR(100) NOT NULL ,
    description TEXT,
    ticket_status VARCHAR(20),
    created_at DATE,
    updated_at DATE
);